apiVersion: apps/v1 
kind: Deployment
metadata:
  name: wordanagrams
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: word
  replicas: 3 
  template: 
    metadata:
      labels:
        app: word
    spec:
      containers:
      - name: word
        image: word
        ports:
        - containerPort: 8000
        volumeMounts:
          - name: secret-volume
            mountPath: /etc/secret-volume
       volumes:
         - name: secret-volume
           secret:
             secretName: test-secret
---
apiVersion: v1
kind: Service
metadata:
  name: wordanagrams
  namespace: default
  labels:
    app: word
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  externalTrafficPolicy: Local
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: word
  type: LoadBalancer
